version: '3'
services:

  solo-auth-mongo-dev:
    image: mongo
    container_name: solo-auth-mongo-dev
    restart: always
    volumes:
      - ./.data:/data/db

  solo-auth-server-dev:
    container_name: solo-auth-server-dev
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
      args: 
        GIT_REPO: 'https://github.com/odjhey/react-mst-gql-accounts-example.git'
    command: "node dist/index.js"
    ports:
      - "4093:8080"
    environment: 
      PORT: "8080"
      mongoURI: "mongodb://solo-auth-mongo-dev:27017/auth"
      authSecret: "90adflkj12309uadsfl"

  solo-auth-webui-dev:
    container_name: solo-auth-webui-dev
    restart: always
    build:
      context: ./webclient
      dockerfile: Dockerfile
      args: 
        GIT_URL: 'https://github.com/odjhey/react-mst-gql-accounts-example.git'
        REACT_APP_ACCOUNTS_SERVER_URI: 'http://ftrnd:4093/graphql'
    command: 'node server.js'
    ports:
      - '4096:8080'
    environment:
      PORT: '8080'
